name: 自动添加用户至同步程序

on:
  push:
    paths:   
      - '**.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Change sync.yml
        run: |
          python change.py

      - name: Prepare to push
        run: |
         git config --global user.name "plana-planetarium"
         git config --global user.email "3412294524@qq.com"
         git add .github/workflows/
         git commit -m 'Update sync.yml'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.KEY }}
