name: 自动添加用户至同步程序

on:
  push:
    paths:   
      - '**.txt'

jobs:
  change:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Change sync.yml
        run: |
          python change.py

      - name: Add
        run: |
          git config --global user.name "plana-planetarium"
          git config --global user.email "3412294524@qq.com"
          git init
          git add .github/workflows/
          git commit -m 'Update sync.yml'

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
