name: 自动同步kemono上的画师文件

on:
  #  schedule:
  #    - cron: '0 11 * * *'
  workflow_dispatch:
    USERNAME:
      type: string
      default: ''
      description: 'test'
      required: false

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      #email
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install ktoolbox-pure-py

      - name: Downloading
        continue-on-error: false
        run: |
          python main.py


      - name: Upload File A.R.O.N.A
        uses: actions/upload-artifact@v3
        with:
          name: A.R.O.N.A
          path: ./Downloads/A.R.O.N.A/
          if-no-files-found: ignore
          retention-days: 7
      - name: Send Email A.R.O.N.A
        run: |
          export $NAME_USER=A.R.O.N.A
          python upload_email.py

